### ISSUE TITLE
Wallpaper Settings button doesn't open anything

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-gui-plugin-shell-companion#19]
Previously, the Settings -> Display -> Wallpaper Settings page would open a selector the the wallpaper but now this button does not open anything

**Comment by JarbasAl** [comment]
is this installed?
https://github.com/OpenVoiceOS/ovos-PHAL-plugin-wallpaper-manager

dont think that functionality has anything to do with the extension, the wallpaper management is OS agnostic   (also works in desktops for example)

**Comment by NeonDaniel** [comment]
It is, but maybe this issue belongs in that repository. I haven't looked into it yet just have a couple reports and validated myself that the page isn't coming up

**Comment by JarbasAl** [comment]
seems related to https://github.com/OpenVoiceOS/ovos-PHAL-plugin-wallpaper-manager/pull/10
