### ISSUE TITLE
Resolve unit test failures

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-gui-plugin-shell-companion#3]
Mocked objects appear to be missing methods (`__set__`?) causing tests to fail

https://github.com/OpenVoiceOS/ovos-gui-plugin-shell-companion/actions/runs/5082456325/jobs/9132197223

**Comment by JarbasAl** [comment]
seems like the bus was passed to the config kwarg

**Comment by JarbasAl** [comment]
closed by #5
